; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples Siri Siri
; https://docs.platformio.org/page/projectconf.html

[platformio]
extra_configs = credentials.ini

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 115200

upload_port = /dev/cu.usbserial-0001
monitor_port = /dev/cu.usbserial-0001

lib_deps =
  adafruit/Adafruit SH110X@^2.1.10
  adafruit/Adafruit GFX Library@^1.11.11
  bblanchon/ArduinoJson@^7.4.1

build_flags =
  -D WIFI_SSID=\"${credentials.wifi_ssid}\"
  -D WIFI_PASSWORD=\"${credentials.wifi_password}\"
  -D API_URL=\"${credentials.api_url}\"
